name: Generate New SLPS and Release

on:
 workflow_dispatch

env:
  base_directory: c:/actions-runner/_work/PythonLib/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  startVM:
    runs-on: ubuntu-latest
    steps:
    
    #Test again
    - name: Login to AZ CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run:
          az vm start -g ${{ secrets.AZURE_RESSOURCE }} -n ${{ secrets.AZURE_VM }}

  pythonCode:
    runs-on: self-hosted
    needs: startVM
    steps:
    
    - name: Checkout PythonLib
      uses: actions/checkout@v2
        
    - name: Checkout PythonLib
      uses: actions/checkout@v2
      with:
        repository: SymphoniaLauren/Tales-of-Rebirth
      
    

    - name: Generate New SLPS
      working-directory: ${{env.base_directory}}
      run: 
        python ${{env.base_directory}}/ToolsTales_Executable.py --game TOR pack SLPS
          
  closeVM:
    runs-on: ubuntu-latest
    needs: pythonCode
    steps:

    - name: Login to AZ CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run:
          az vm stop -g ${{ secrets.AZURE_RESSOURCE }} -n ${{ secrets.AZURE_VM }}
