
name: Generate New SLPS and Release

on:
 workflow_dispatch

env:
  base_directory: c:/actions-runner/_work/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  startVM:
    runs-on: ubuntu-latest
    steps:
    
    #Test again
    - name: Login to AZ CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run:
          az vm start -g ${{ secrets.AZURE_RESSOURCE }} -n ${{ secrets.AZURE_VM }}
